transcript on
if ![file isdirectory verilog_libs] {
	file mkdir verilog_libs
}

vlib verilog_libs/altera_ver
vmap altera_ver ./verilog_libs/altera_ver
vlog -vlog01compat -work altera_ver {d:/intelfpga/17.1/quartus/eda/sim_lib/altera_primitives.v}

vlib verilog_libs/lpm_ver
vmap lpm_ver ./verilog_libs/lpm_ver
vlog -vlog01compat -work lpm_ver {d:/intelfpga/17.1/quartus/eda/sim_lib/220model.v}

vlib verilog_libs/sgate_ver
vmap sgate_ver ./verilog_libs/sgate_ver
vlog -vlog01compat -work sgate_ver {d:/intelfpga/17.1/quartus/eda/sim_lib/sgate.v}

vlib verilog_libs/altera_mf_ver
vmap altera_mf_ver ./verilog_libs/altera_mf_ver
vlog -vlog01compat -work altera_mf_ver {d:/intelfpga/17.1/quartus/eda/sim_lib/altera_mf.v}

vlib verilog_libs/altera_lnsim_ver
vmap altera_lnsim_ver ./verilog_libs/altera_lnsim_ver
vlog -sv -work altera_lnsim_ver {d:/intelfpga/17.1/quartus/eda/sim_lib/altera_lnsim.sv}

vlib verilog_libs/cyclonev_ver
vmap cyclonev_ver ./verilog_libs/cyclonev_ver
vlog -vlog01compat -work cyclonev_ver {d:/intelfpga/17.1/quartus/eda/sim_lib/mentor/cyclonev_atoms_ncrypt.v}
vlog -vlog01compat -work cyclonev_ver {d:/intelfpga/17.1/quartus/eda/sim_lib/mentor/cyclonev_hmi_atoms_ncrypt.v}
vlog -vlog01compat -work cyclonev_ver {d:/intelfpga/17.1/quartus/eda/sim_lib/cyclonev_atoms.v}

vlib verilog_libs/cyclonev_hssi_ver
vmap cyclonev_hssi_ver ./verilog_libs/cyclonev_hssi_ver
vlog -vlog01compat -work cyclonev_hssi_ver {d:/intelfpga/17.1/quartus/eda/sim_lib/mentor/cyclonev_hssi_atoms_ncrypt.v}
vlog -vlog01compat -work cyclonev_hssi_ver {d:/intelfpga/17.1/quartus/eda/sim_lib/cyclonev_hssi_atoms.v}

vlib verilog_libs/cyclonev_pcie_hip_ver
vmap cyclonev_pcie_hip_ver ./verilog_libs/cyclonev_pcie_hip_ver
vlog -vlog01compat -work cyclonev_pcie_hip_ver {d:/intelfpga/17.1/quartus/eda/sim_lib/mentor/cyclonev_pcie_hip_atoms_ncrypt.v}
vlog -vlog01compat -work cyclonev_pcie_hip_ver {d:/intelfpga/17.1/quartus/eda/sim_lib/cyclonev_pcie_hip_atoms.v}

if {[file exists rtl_work]} {
	vdel -lib rtl_work -all
}
vlib rtl_work
vmap work rtl_work

vlib NoC_QSYS
vmap NoC_QSYS NoC_QSYS
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/NoC_QSYS.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/altera_reset_controller.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/altera_reset_synchronizer.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_avalon_st_adapter_004.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_avalon_st_adapter.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_mm_interconnect_0.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_mm_interconnect_0_avalon_st_adapter.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/altera_avalon_sc_fifo.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_nios2_11.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_nios2_11_cpu.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_nios2_11_cpu_debug_slave_sysclk.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_nios2_11_cpu_debug_slave_tck.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_nios2_11_cpu_debug_slave_wrapper.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_nios2_11_cpu_test_bench.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_nios2_10.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_nios2_10_cpu.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_nios2_10_cpu_debug_slave_sysclk.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_nios2_10_cpu_debug_slave_tck.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_nios2_10_cpu_debug_slave_wrapper.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_nios2_10_cpu_test_bench.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_nios2_01.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_nios2_01_cpu.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_nios2_01_cpu_debug_slave_sysclk.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_nios2_01_cpu_debug_slave_tck.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_nios2_01_cpu_debug_slave_wrapper.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_nios2_01_cpu_test_bench.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_nios2_00.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_nios2_00_cpu.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_nios2_00_cpu_debug_slave_sysclk.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_nios2_00_cpu_debug_slave_tck.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_nios2_00_cpu_debug_slave_wrapper.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_nios2_00_cpu_test_bench.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_jtag_uart_0.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_fifo_source_00.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_fifo_sink_00.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_data_mem_11.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_data_mem_10.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_data_mem_01.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_data_mem_00.v}
vlog -vlog01compat -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/wrapper.v}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_avalon_st_adapter_004_timing_adapter_0.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_avalon_st_adapter_004_error_adapter_0.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_avalon_st_adapter_004_channel_adapter_0.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_avalon_st_adapter_004_data_format_adapter_0.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_avalon_st_adapter_timing_adapter_0.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_avalon_st_adapter_timing_adapter_0_fifo.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_avalon_st_adapter_error_adapter_0.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_avalon_st_adapter_channel_adapter_0.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_avalon_st_adapter_data_format_adapter_0.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_avalon_st_adapter_data_format_adapter_0_state_ram.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_avalon_st_adapter_data_format_adapter_0_data_ram.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_irq_mapper.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_mm_interconnect_0_avalon_st_adapter_error_adapter_0.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_mm_interconnect_0_rsp_mux_004.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/altera_merlin_arbitrator.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_mm_interconnect_0_rsp_mux.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_mm_interconnect_0_rsp_demux_002.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_mm_interconnect_0_rsp_demux.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_mm_interconnect_0_cmd_mux_002.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_mm_interconnect_0_cmd_mux_001.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_mm_interconnect_0_cmd_mux.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_mm_interconnect_0_cmd_demux_004.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_mm_interconnect_0_cmd_demux.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_mm_interconnect_0_router_028.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_mm_interconnect_0_router_027.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_mm_interconnect_0_router_022.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_mm_interconnect_0_router_021.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_mm_interconnect_0_router_016.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_mm_interconnect_0_router_015.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_mm_interconnect_0_router_010.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_mm_interconnect_0_router_009.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_mm_interconnect_0_router_008.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_mm_interconnect_0_router_007.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_mm_interconnect_0_router_006.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_mm_interconnect_0_router_005.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_mm_interconnect_0_router_004.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_mm_interconnect_0_router_003.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_mm_interconnect_0_router_002.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_mm_interconnect_0_router_001.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NoC_QSYS_mm_interconnect_0_router.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/altera_merlin_slave_agent.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/altera_merlin_burst_uncompressor.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/altera_merlin_master_agent.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/altera_merlin_slave_translator.sv}
vlog -sv -work NoC_QSYS +incdir+C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/altera_merlin_master_translator.sv}
vcom -93 -work NoC_QSYS {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/ConnectionPack.vhd}
vcom -93 -work NoC_QSYS {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/FilePack.vhd}
vcom -93 -work NoC_QSYS {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/RouterA.vhd}
vcom -93 -work NoC_QSYS {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/Node.vhd}
vcom -93 -work NoC_QSYS {C:/Users/Mahdi2016/Desktop/ThesisProject/ThesisProject/QsysComponents/NIOS_with_NoC/NoC_QSYS/synthesis/submodules/NOC.vhd}

